@ECHO OFF
::
::literaly rpg game but fast and good
::
SETLOCAL ENABLEDELAYEDEXPANSION
::1 IF YOUR TURN
SET TURN=0
SET TURNCOUNT=0
SET PLAYER.ISBLOCKING=0
SET ENEMY.ISBLOCKING=0
SET LEVELUP=0
SET DEBUG=0

:PICKCLASS
ECHO CHOOSE YOUR CLASS
ECHO 1-WARRIOR
ECHO 2-THEIF
ECHO 3-WIZARD
CHOICE /C Z123 /N
CLS
IF %ERRORLEVEL%==1 (
  SET DEBUG=1
)
IF %ERRORLEVEL%==2 (
  CALL :CREATEPLAYER WARRIOR,10,15,2,2,2,10,6
  GOTO INTRO
)
IF %ERRORLEVEL%==3 (
  CALL :CREATEPLAYER THEIF,15,10,1,1,3,25,12
  GOTO INTRO
)
IF %ERRORLEVEL%==4 (
  CALL :CREATEPLAYER WIZARD,10,10,1,1,1,15,8
  GOTO INTRO
)
:: DO NOT PUT ANYTHING BETWEEN THESE
:PICKCLASS2
CHOICE /C Z123 /N
CLS
IF %ERRORLEVEL%==1 (
  SET /A DEBUG+=1
)
IF %DEBUG% GEQ 2 @ECHO ON
IF %ERRORLEVEL%==2 (
  CALL :CREATEPLAYER WARRIOR,10,15,2,2,2,10,6
  GOTO INTRO
)
IF %ERRORLEVEL%==3 (
  CALL :CREATEPLAYER THEIF,15,10,1,1,3,25,12
  GOTO INTRO
)
IF %ERRORLEVEL%==4 (
  CALL :CREATEPLAYER WIZARD,10,10,1,1,1,15,8
  GOTO INTRO
)

::1-CLASS
::2-GOLD
::3-MAXHEALTH
::4-ARMOR
::5-ARMOR.SHEILD
::6-WEAPON (DAMAGE)
::7-CHARM
::8-SPEED
:CREATEPLAYER
SET PLAYER.CLASS=%~1
SET PLAYER.EXP=0
SET PLAYER.GOLD=%~2
CALL :CREATECHARACTER PLAYER,1,%~3,%~4,%~5,%~6,,%~8
SET PLAYER.CHARM=%~7
EXIT /B 0

::1-NAME
::2-LEVEL
::3-MAXHEALTH
::4-ARMOR
::5-ARMOR.SHEILD
::6-DAMAGE
::7-DECEPTION
::8-SPEED
:CREATECHARACTER
SET %~1.LEVEL=%~2
SET %~1.MAXHEALTH=%~3
SET %~1.HEALTH=%~3
SET %~1.ARMOR=%~4
SET %~1.ARMOR.SHEILD=%~5
SET %~1.DAMAGE=%~6
SET %~1.DECEPTION=%~7
SET %~1.SPEED=%~8
EXIT /B 0

:REMOVECHARACTER
CALL :CREATECHARACTER %~1
EXIT /B 0

:INTRO
IF %DEBUG% GEQ 1 GOTO INTRO.SKIP
ECHO YOU OPEN YOU EYES AND LOOK AROUND
ECHO YOU APEAR TO BE LAYING ON THE GROUND
PAUSE
CLS
ECHO YOU GET UP AND NOTICE YOUR BACK HURTS AS YOU HAVE
ECHO BEEN LAYING ON A BIG ROCK THIS WHOLE TIME
PAUSE
CLS
ECHO YOU LOOK AROUND AND APPEAR TO BE IN THE MIDDLE OF A FEILD
ECHO WITH NO IDEA HOW YOU GOT THERE
PAUSE
CLS
ECHO IN THE DISTANCE YOU CAN SEE WHAT APPEARS TO BE
ECHO A SMALL TOWN
ECHO YOU DECIDE TO MAKE YOUR WAY OVER THERE
ECHO MABEY EVEN SOMBODY WILL KNOW HOW YOU GOT HERE
PAUSE
CLS
ECHO YOU FINNALY ARRIVE AT THE TOWN
ECHO AND ARE GREETED BY A GAURD AT THE GATES
PAUSE
CLS
:INTRO.SKIP
ECHO GAURD - "HEY, WHO ARE YOU. NO VISITORS ALLOWED, KINGS ORDERS"
ECHO THE GAURD APPEARS TO BE TELLING YOU TO LEAVE
CALL :CREATECHARACTER KNIGHT,1,15,2,2,1,12,8
ECHO 1-TELL HIM YOU ARE A TRAVELLING MERCHANT AND ARE HERE TO SELL YOUR SUPPLIES (PERSUASION)
ECHO 2-DRAW WEAPON (FIGHT)
ECHO 3-ASK WHY YOU CANT COME IN
CHOICE /C 123 /N
CLS
IF %ERRORLEVEL%==1 GOTO INTRO.A
IF %ERRORLEVEL%==2 GOTO INTRO.B
IF %ERRORLEVEL%==3 GOTO INTRO.C

:INTRO.A
CALL :CHANCE %PLAYER.CHARM%,%KNIGHT.DECEPTION%,R
IF %R%==0 (
  ECHO PERSUASION ATTEMPT FAILED
  PAUSE
  CLS
  GOTO INTRO.B
)
ECHO GUARD - "FINE, YOU CAN GO IN"
PAUSE
CLS
GOTO GREENVILLE.FIRST

:INTRO.B
ECHO GUARD - "OH, YOU'RE DEAD NOW"
PAUSE
CALL :COMBATINIT KNIGHT
GOTO GREENVILLE.FIRST

:INTRO.C
ECHO GAURD - "THAT IS NONE OF YOUR BUSISNESS"
ECHO 1-POINT WEAPON AT THEM (INTIMIDATION)
ECHO 2-FINE
CHOICE /C 12 /N
CLS
IF %ERRORLEVEL%==1 GOTO INTRO.D
ECHO 1-TELL HIM YOU ARE A TRAVELLING MERCHANT AND ARE HERE TO SELL YOUR SUPPLIES (PERSUASION)
ECHO 2-DRAW WEAPON (FIGHT)
CHOICE /C 12 /N
IF %ERRORLEVEL%==1 GOTO INTRO.A
GOTO INTRO.B

:INTRO.D
CALL :CHANCE %PLAYER.CHARM%,%KNIGHT.DECEPTION%,R
IF %R%==0 (
  ECHO PERSUASION ATTEMPT FAILED
  PAUSE
  CLS
  GOTO INTRO.B
)
ECHO GUARD - "FINE, FINE, IT IS BECAUSE THERE HAVE BEEN SPIES WANDERING AROUND RECENTLY"
ECHO "NOW WHAT DO YOU WANT?"
PAUSE
CLS
ECHO 1-TELL HIM YOU ARE A TRAVELLING MERCHANT AND ARE HERE TO SELL YOUR SUPPLIES (PERSUASION)
ECHO 2-DRAW WEAPON (FIGHT)
CHOICE /C 12 /N
IF %ERRORLEVEL%==1 GOTO INTRO.A
GOTO INTRO.B

:GREENVILLE.FIRST
CLS
ECHO YOU ENTER THE CITY AND TO YOUR DISSAPOINTMENT,
ECHO YOU FIND THAT IT ISNT MUCH OF A CITY,
ECHO REGARDLESS, YOU DECIDE TO GO FURTHER INTO THE CITY
PAUSE
CLS
:GREENVILLE
IF %LEVELUP% GEQ 1 GOTO GREENVILLE.LEVELUP
ECHO 1-MARKET PLACE
ECHO 2-TAVERN
CHOICE /C 12 /N
SET CHOICE=%ERRORLEVEL%
IF %CHOICE%==1 CALL :GREENVILLE.MARKETPLACE
IF %CHOICE%==2 CALL :GREENVILLE.TAVERN
GOTO GREENVILLE

:GREENVILLE.LEVELUP
ECHO 1-LEVELUP
ECHO 2-MARKET PLACE
ECHO 3-TAVERN
CHOICE /C 123 /N
SET CHOICE=%ERRORLEVEL%
IF %CHOICE%==1 CALL :LEVELUP
IF %CHOICE%==2 CALL :GREENVILLE.MARKETPLACE
IF %CHOICE%==3 CALL :GREENVILLE.TAVERN
GOTO GREENVILLE

::1-MAX CHANCE
::2-CHANCE TO BEAT
::3-RETURN 1 OR 0
:CHANCE
SET R=%~1
SET /A I=%RANDOM%*%R%/32768
SET /A I2=%~2
IF %I% GEQ %I2% (
  SET %~3=1
) ELSE (
  SET %~3=0
)
EXIT /B 0

::1-ENEMY
:COMBATINIT
SET TURNCOUNT=0
SET TURN=1
SET ENEMY.NAME=%~1
ECHO %ENEMY.NAME%
PAUSE
IF "%PLAYER.SPEED%" LEQ "!%ENEMY.NAME%.SPEED!" SET TURN=0
ECHO %TURN%
PAUSE
CALL :COMBAT %ENEMY.NAME%
EXIT /B 0

:COMBAT
CLS
SET ENEMY.NAME=%~1
IF %PLAYER.HEALTH% LEQ 0 GOTO DEAD
IF !%~1.HEALTH! LEQ 0 (
  CALL :POSTCOMBAT
  EXIT /B 0
)
ECHO HEALTH: %PLAYER.HEALTH% / %PLAYER.MAXHEALTH%
ECHO ARMOR: %PLAYER.ARMOR%
ECHO -
ECHO -
ECHO -
IF %TURNCOUNT% GEQ 1 ( ECHO %ENEMY.NAME% %ENEMY.LASTTURN% ) ELSE ( ECHO -)
ECHO -
ECHO ARMOR: !%ENEMY.NAME%.ARMOR!
ECHO HEALTH: !%ENEMY.NAME%.HEALTH! / !%ENEMY.NAME%.MAXHEALTH!
ECHO -
IF %TURN%==1 ( CALL :TURN )
IF %TURN%==0 ( CALL :ENEMYTURN %ENEMY.NAME% )
SET /A TURNCOUNT+=1
GOTO COMBAT

:TURN
IF %PLAYER.ISBLOCKING%==1 (
  SET PLAYER.ISBLOCKING=0
  SET /A PLAYER.ARMOR-=%PLAYER.ARMOR.SHEILD%
)
ECHO 1-ATTACK
ECHO 2-BLOCK
CHOICE /C 12 /N
SET CHOICE=%ERRORLEVEL%
IF %CHOICE%==1 CALL :ATTACK %ENEMY.NAME%,%PLAYER.WEAPON%
IF %CHOICE%==2 CALL :BLOCK PLAYER
SET TURN=0
EXIT /B 0

:ENEMYTURN
IF %ENEMY.ISBLOCKING%==1 (
  SET ENEMY.ISBLOCKING=0
  SET /A ENEMY.ARMOR-=!%ENEMY.NAME%.ARMOR.SHEILD!
)
IF %~1==KNIGHT CALL :KNIGHT
SET TURN=1
EXIT /B 0

:KNIGHT
SET /A CHOICE=%RANDOM%*1/32768
IF %CHOICE%==0 (
  SET "ENEMY.LASTTURN=ATTACKED YOU"
  CALL :ATTACK PLAYER,!%ENEMY.NAME%.WEAPON!
)
IF %CHOICE%==1 (
  SET ENEMY.LASTTURN=BLOCKED
  CALL :BLOCK ENEMY
)
EXIT /B 0

::1-TARGET
::2-DAMAGE
:ATTACK
SET TARGET=%~1
SET DAMAGE=%~2
SET /A TEMP=%DAMAGE/!%TARGET%.ARMOR!
IF %TEMP%==0 SET TEMP=1
SET /A %TARGET%.HEALTH-=%TEMP%
EXIT /B 0

::1-TARGET
:BLOCK
SET TARGET=%~1
SET %TARGET%.ISBLOCKING=1
SET /A %TARGET%.ARMOR+=!%TARGET%.ARMOR.SHEILD!
EXIT /B 0

::1-TARGET
:ENEMYBLOCK
SET TARGET=%~1
SET %TARGET%.ISBLOCKING=1
SET /A %TARGET%.ARMOR+=!%ENEMY.NAME%.ARMOR.SHEILD!
EXIT /B 0

:POSTCOMBAT
CALL :REWARD.%ENEMY.NAME%
SET /A PLAYER.GOLD+=%GR%
SET /A PLAYER.EXP+=%ER%
CALL :REMOVECHARACTER %ENEMY.NAME%
SET ENEMY.NAME=
EXIT /B 0

:REWARD.KNIGHT
SET GR=%RANDOM%*3/32768+1
SET ER=%RANDOM%*3/32768+1
EXIT /B 0

:DEAD
CLS
FOR /L %%I IN (1,1,10) DO (
  SET /A I-=1
  ECHO YOU DIED
)
EXIT