@ECHO OFF
::
::literaly rpg game but fast and good
::
SETLOCAL ENABLEDELAYEDEXPANSION
::1 IF YOUR TURN
SET TURN=0
SET TURNCOUNT=0
SET PLAYER.ISBLOCKING=0
SET ENEMY.ISBLOCKING=0
SET LEVELUP=0
SET NEXTLEVELUP=6
SET DEBUG=0
SET PLAYER.LEVEL=1
SET MAINQUEST=0
SET CITY=

:PICKCLASS
CLS
ECHO CHOOSE YOUR CLASS
ECHO 1-WARRIOR
ECHO 2-ROGUE
ECHO 3-WIZARD
ECHO 4-LOAD CHARACTER
CHOICE /C Z1234 /N
IF %ERRORLEVEL%==1 (
  SET /A DEBUG+=1
  GOTO PICKCLASS
)
IF %DEBUG% GEQ 2 @ECHO ON
IF %ERRORLEVEL%==2 (
  CALL :CREATEPLAYER WARRIOR,15,0,12,5,10,6,5
  CALL :CREATEPLAYER.EQUIP 2,2,1
  SET PLAYER.GOLD=10
  GOTO INTRO
)
IF %ERRORLEVEL%==3 (
  CALL :CREATEPLAYER THEIF,10,0,5,7,25,12,15
  CALL :CREATEPLAYER.EQUIP 1,1,2
  SET PLAYER.GOLD=15
  GOTO INTRO
)
IF %ERRORLEVEL%==4 (
  CALL :CREATEPLAYER WIZARD,10,5,5,12,15,8,5
  CALL :CREATEPLAYER.EQUIP 1,1,1
  SET PLAYER.GOLD=10
  GOTO INTRO
)
IF %ERRORLEVEL%==5 (
  GOTO LOAD
)

::1-CLASS
::2-MAXHEALTH
::3-MAXMANA
::4-STRENGTH
::5-INT
::6-CHARM
::7-SPEED
::8-LUCK
:CREATEPLAYER
SET PLAYER.CLASS=%~1
SET PLAYER.EXP=0
SET PLAYER.MAXMANA=%~3
SET PLAYER.MANA=%~3
SET PLAYER.STRENGTH=%~4
SET PLAYER.INT=%~5
CALL :CREATECHARACTER PLAYER,%~2,%~6,%~7,%~8
EXIT /B 0

::1-ARMOR
::2-ARMOR.SHEILD
::3-WEAPON (DAMAGE)
:CREATEPLAYER.EQUIP
SET PLAYER.ARMOR=%~1
SET PLAYER.ARMOR.SHEILD=%~2
SET PLAYER.DAMAGE=%~3
EXIT /B 0

::1-NAME
::2-MAXHEALTH
::3-CHARM
::4-SPEED
::5-LUCK
:CREATECHARACTER
SET ENEMY.NAME=%~1
SET %~1.MAXHEALTH=%~2
SET %~1.HEALTH=%~2
SET %~1.CHARM=%~3
SET %~1.SPEED=%~4
SET %~1.LUCK=%~5
EXIT /B 0

::1-ARMOR
::2-ARMOR.SHEILD
::3-WEAPON (DAMAGE)
:CREATECHARACTER.EQUIP
SET %ENEMY.NAME%.ARMOR=%~1
SET %ENEMY.NAME%.ARMOR.SHEILD=%~2
SET %ENEMY.NAME%.DAMAGE=%~3
EXIT /B 0

:REMOVECHARACTER
CALL :CREATECHARACTER %~1
EXIT /B 0

:CLS
IF %DEBUG% GEQ 2 EXIT /B 0
CLS
EXIT /B 0

:SAVE
ECHO PLAYER.CLASS=%PLAYER.CLASS% > SAVEDATA.txt
(
ECHO PLAYER.LEVEL=%PLAYER.LEVEL%
ECHO PLAYER.EXP=%PLAYER.EXP%
ECHO PLAYER.MAXHEALTH=%PLAYER.MAXHEALTH%
ECHO PLAYER.MAXMANA=%PLAYER.MAXMANA%
ECHO PLAYER.STRENGTH=%PLAYER.STRENGTH%
ECHO PLAYER.INT=%PLAYER.INT%
ECHO PLAYER.CHARM=%PLAYER.CHARM%
ECHO PLAYER.SPEED=%PLAYER.SPEED%
ECHO PLAYER.LUCK=%PLAYER.LUCK%
ECHO PLAYER.ARMOR=%PLAYER.ARMOR%
ECHO PLAYER.ARMOR.SHEILD=%PLAYER.ARMOR.SHEILD%
ECHO PLAYER.WEAPON=%PLAYER.WEAPON%
ECHO LEVELUP=%LEVELUP%
ECHO NEXTLEVELUP=%NEXTLEVELUP%
ECHO MAINQUEST=%MAINQUEST%
ECHO CITY=%CITY%
)>> SAVEDATA.txt
EXIT /B 0

:LOAD
FOR /F "usebackq tokens=1* delims==" %%A IN (SAVEDATA.txt) DO SET %%A=%%B
GOTO %CITY%

:INTRO
CALL :CLS
IF %DEBUG% GEQ 1 GOTO INTRO.SKIP
ECHO YOU OPEN YOU EYES AND LOOK AROUND
ECHO YOU APEAR TO BE LAYING ON THE GROUND
PAUSE
CALL :CLS
ECHO YOU GET UP AND NOTICE YOUR BACK HURTS AS YOU HAVE
ECHO BEEN LAYING ON A BIG ROCK THIS WHOLE TIME
PAUSE
CALL :CLS
ECHO YOU LOOK AROUND AND APPEAR TO BE IN THE MIDDLE OF A FEILD
ECHO WITH NO IDEA HOW YOU GOT THERE
PAUSE
CALL :CLS
ECHO IN THE DISTANCE YOU CAN SEE WHAT APPEARS TO BE
ECHO A SMALL TOWN
ECHO YOU DECIDE TO MAKE YOUR WAY OVER THERE
ECHO MABEY EVEN SOMBODY WILL KNOW HOW YOU GOT HERE
PAUSE
CALL :CLS
ECHO YOU FINNALY ARRIVE AT THE TOWN
ECHO AND ARE GREETED BY A GAURD AT THE GATES
PAUSE
CALL :CLS
:INTRO.SKIP
ECHO GAURD - "HEY, WHO ARE YOU. NO VISITORS ALLOWED, KINGS ORDERS"
ECHO THE GAURD APPEARS TO BE TELLING YOU TO LEAVE
CALL :CREATECHARACTER KNIGHT,15,12,8,5
CALL :CREATECHARACTER.EQUIP 2,1,1
ECHO 1-TELL HIM YOU ARE A TRAVELLING MERCHANT AND ARE HERE TO SELL YOUR SUPPLIES (PERSUASION)
ECHO 2-DRAW WEAPON (FIGHT)
ECHO 3-ASK WHY YOU CANT COME IN
CHOICE /C 123 /N
SET CHOICE=%ERRORLEVEL%
CALL :CLS
SET P=0
IF %CHOICE%==1 CALL :PERSUADE KNIGHT,P
IF %P%==1 GOTO INTRO.A
IF %CHOICE%==3 GOTO INTRO.C
GOTO INTRO.B

:INTRO.A
ECHO GUARD - "FINE, YOU CAN GO IN"
PAUSE
CALL :CLS
GOTO GREENVILLE.FIRST

:INTRO.B
ECHO GUARD - "OH, YOU'RE DEAD NOW"
PAUSE
CALL :COMBATINIT KNIGHT
GOTO GREENVILLE.FIRST

:INTRO.C
ECHO GAURD - "THAT IS NONE OF YOUR BUSISNESS"
ECHO 1-POINT WEAPON AT THEM (INTIMIDATION)
ECHO 2-FINE
CHOICE /C 12 /N
CALL :CLS
SET P=0
IF %ERRORLEVEL%==1 CALL :PERSUADE KNIGHT,P
%P%==1 GOTO INTRO.D
IF %P%==0 AND %ERRORLEVEL% NEQ 2 GOTO INTRO.B
ECHO 1-TELL HIM YOU ARE A TRAVELLING MERCHANT AND ARE HERE TO SELL YOUR SUPPLIES (PERSUASION)
ECHO 2-DRAW WEAPON (FIGHT)
CHOICE /C 12 /N
SET P=0
IF %ERRORLEVEL%==1 CALL :PERSUADE KNIGHT,P
%P%==1 GOTO INTRO.A
GOTO INTRO.B

:INTRO.D
ECHO GUARD - "FINE, FINE, IT IS BECAUSE THERE HAVE BEEN SPIES WANDERING AROUND RECENTLY"
ECHO "NOW WHAT DO YOU WANT?"
PAUSE
CALL :CLS
ECHO 1-TELL HIM YOU ARE A TRAVELLING MERCHANT AND ARE HERE TO SELL YOUR SUPPLIES (PERSUASION)
ECHO 2-DRAW WEAPON (FIGHT)
CHOICE /C 12 /N
SET P=0
IF %ERRORLEVEL%==1 CALL :PERSUADE KNIGHT,P
IF %ERRORLEVEL%==2 GOTO INTRO.B
IF %P%==1 GOTO INTRO.A
GOTO INTRO.B

:GREENVILLE.FIRST
CALL :CLS
SET MAINQUEST=1
ECHO YOU ENTER THE CITY AND TO YOUR DISSAPOINTMENT,
ECHO YOU FIND THAT IT ISNT MUCH OF A CITY,
ECHO REGARDLESS, YOU DECIDE TO GO FURTHER INTO THE CITY
PAUSE
:GREENVILLE
CALL :CLS
SET CITY=GREENVILLE
SET PLAYER.HEALTH=%PLAYER.MAXHEALTH%
SET PLAYER.MANA=%PLAYER.MAXMANA%
IF %PLAYER.EXP% GEQ %NEXTLEVELUP% CALL :CALCLEVELUP
IF %LEVELUP% GEQ 1 GOTO GREENVILLE.LEVELUP
ECHO 1-MARKET PLACE
ECHO 2-TAVERN
ECHO 3-LEAVE
ECHO 4-SAVE
IF %MAINQUEST%==1 ECHO 5-WANDER STREETS
IF %MAINQUEST%==1 (
  CHOICE /C 12345 /N 
) ELSE (
  CHOICE /C 1234 /N
)
SET CHOICE=%ERRORLEVEL%
IF %CHOICE%==1 CALL :GREENVILLE.MARKETPLACE
IF %CHOICE%==2 CALL :GREENVILLE.TAVERN
IF %CHOICE%==3 CALL :LEAVE
IF %CHOICE%==4 CALL :SAVE
IF %CHOICE%==5 CALL :GREENVILLE.STREETS
GOTO GREENVILLE

:GREENVILLE.LEVELUP
ECHO 1-LEVELUP
ECHO 2-MARKET PLACE
ECHO 3-TAVERN
ECHO 4-LEAVE
ECHO 5-SAVE
IF %MAINQUEST%==1 ECHO 6-WANDER STREETS
IF %MAINQUEST%==1 (
  CHOICE /C 123456 /N 
) ELSE (
  CHOICE /C 12345 /N
)
SET CHOICE=%ERRORLEVEL%
IF %CHOICE%==1 CALL :LEVELUP
IF %CHOICE%==2 CALL :GREENVILLE.MARKETPLACE
IF %CHOICE%==3 CALL :GREENVILLE.TAVERN
IF %CHOICE%==4 CALL :LEAVE
IF %CHOICE%==5 CALL :SAVE
IF %CHOICE%==6 CALL :GREENVILLE.STREETS
GOTO GREENVILLE

::1-MAX CHANCE
::2-CHANCE TO BEAT
::3-RETURN 1 OR 0
:CHANCE
SET R=%~1
SET I=
SET I2=
SET /A "I=%RANDOM%*%R%/32767"
SET /A "I2=%RANDOM%*%~2/32767"
IF %I% GEQ %I2% (
  SET %~3=1
) ELSE (
  SET %~3=0
)
EXIT /B 0

::1-TARGET
::2-RETURN 1 OR 0
:PERSUADE
SET ENEMY.NAME=%~1
CALL :CHANCE %PLAYER.CHARM%,!%ENEMY.NAME%.CHARM!,R
IF %R%==0 (
  ECHO PERSUASION ATTEMPT FAILED
  PAUSE
  CALL :CLS
  SET %~2=0
) ELSE (
  CALL :POSTCOMBAT
  SET %~2=1
)
EXIT /B 0

::1-ENEMY
:COMBATINIT
SET TURNCOUNT=0
SET TURN=1
SET ENEMY.NAME=%~1
ECHO %ENEMY.NAME%
IF "%PLAYER.SPEED%" LEQ "!%ENEMY.NAME%.SPEED!" SET TURN=0
ECHO %TURN%
CALL :COMBAT %ENEMY.NAME%
EXIT /B 0

:COMBAT
CALL :CLS
SET ENEMY.NAME=%~1
IF %PLAYER.HEALTH% LEQ 0 GOTO DEAD
IF !%ENEMY.NAME%.HEALTH! LEQ 0 (
  CALL :POSTCOMBAT
  EXIT /B 0
)
ECHO HEALTH: %PLAYER.HEALTH% / %PLAYER.MAXHEALTH%
ECHO ARMOR: %PLAYER.ARMOR%
ECHO -
ECHO -
ECHO -
IF %TURNCOUNT% GEQ 1 ( ECHO %ENEMY.NAME% %ENEMY.LASTTURN% ) ELSE ( ECHO -)
ECHO -
ECHO ARMOR: !%ENEMY.NAME%.ARMOR!
ECHO HEALTH: !%ENEMY.NAME%.HEALTH! / !%ENEMY.NAME%.MAXHEALTH!
ECHO -
IF %TURN%==1 ( CALL :TURN )
IF %TURN%==0 ( CALL :ENEMYTURN %ENEMY.NAME% )
SET /A TURNCOUNT+=1
GOTO COMBAT

:TURN
IF %PLAYER.ISBLOCKING%==1 (
  SET PLAYER.ISBLOCKING=0
  SET /A PLAYER.ARMOR-=%PLAYER.ARMOR.SHEILD%
)
ECHO 1-ATTACK
ECHO 2-BLOCK
CHOICE /C 12 /N
SET CHOICE=%ERRORLEVEL%
IF %CHOICE%==1 CALL :ATTACK %ENEMY.NAME%,PLAYER,%PLAYER.WEAPON%
IF %CHOICE%==2 CALL :BLOCK PLAYER
SET TURN=0
EXIT /B 0

:ENEMYTURN
IF %ENEMY.ISBLOCKING%==1 (
  SET ENEMY.ISBLOCKING=0
  SET /A ENEMY.ARMOR-=!%ENEMY.NAME%.ARMOR.SHEILD!
)
IF %~1==KNIGHT CALL :KNIGHT
SET TURN=1
EXIT /B 0

:KNIGHT
SET /A CHOICE=%RANDOM%*1/32768
IF %CHOICE%==0 (
  SET "ENEMY.LASTTURN=ATTACKED YOU"
  CALL :ATTACK PLAYER,KNIGHT,!%ENEMY.NAME%.WEAPON!
)
IF %CHOICE%==1 (
  SET ENEMY.LASTTURN=BLOCKED
  CALL :BLOCK ENEMY
)
EXIT /B 0

::1-TARGET
::2-ATTACKER
::2-DAMAGE
:ATTACK
SET CRIT=1
SET TARGET=%~1
SET ATTACKER=%~2
SET DAMAGE=%~3
SET /A C=%RANDOM%*50/32767
IF %C% LEQ !%ATTACKER%.LUCK! SET CRIT=2
SET /A TEMP=%DAMAGE/!%TARGET%.ARMOR!
IF %TEMP%==0 SET TEMP=1
SET /A %TARGET%.HEALTH-=%TEMP%*%CRIT%
EXIT /B 0

::1-TARGET
:BLOCK
SET TARGET=%~1
SET %TARGET%.ISBLOCKING=1
SET /A %TARGET%.ARMOR+=!%TARGET%.ARMOR.SHEILD!
EXIT /B 0

::1-TARGET
:ENEMYBLOCK
SET TARGET=%~1
SET %TARGET%.ISBLOCKING=1
SET /A %TARGET%.ARMOR+=!%ENEMY.NAME%.ARMOR.SHEILD!
EXIT /B 0

:LEVELUP
CALL :CLS
ECHO WHAT WOULD YOU LIKE TO LEVEL
ECHO 1-HEALTH
ECHO 2-MANA
ECHO 3-STRENGTH
ECHO 4-SPEED
ECHO 5-INT
ECHO 6-CHARM
ECHO 7-LUCK
CHOICE /C 1234567 /N
SET /A LEVELUP-=1
IF %ERRORLEVEL%==1 SET /A PLAYER.MAXHEALTH+=1
IF %ERRORLEVEL%==2 SET /A PLAYER.MAXMANA+=1
IF %ERRORLEVEL%==3 SET /A PLAYER.STRENGTH+=1
IF %ERRORLEVEL%==4 SET /A PLAYER.SPEED+=1
IF %ERRORLEVEL%==5 SET /A PLAYER.INT+=1
IF %ERRORLEVEL%==6 SET /A PLAYER.CHARM+=1
IF %ERRORLEVEL%==7 SET /A PLAYER.LUCK+=1
IF %LEVELUP% GEQ 1 GOTO LEVELUP
EXIT /B 0

:CALCLEVELUP
SET /A PLAYER.EXP-=%NEXTLEVELUP%
SET /A LEVELUP+=1
SET /A PLAYER.LEVEL+=1
SET /A NEXTLEVELUP=%PLAYER.LEVEL%*5+%PLAYER.LEVEL%
IF %PLAYER.EXP% GEQ %NEXTLEVELUP% GOTO CALCLEVELUP
EXIT /B 0

:POSTCOMBAT
SET LUCK=%PLAYER.LUCK%
CALL :REWARD.%ENEMY.NAME% GR,ER
SET /A PLAYER.GOLD+=%GR%*%LUCK%/10+1
SET /A PLAYER.EXP+=%ER%*%LUCK%/10+1
CALL :REMOVECHARACTER %ENEMY.NAME%
SET ENEMY.NAME=
EXIT /B 0

:REWARD.KNIGHT
SET /A %~1=%RANDOM%*6/32767+1
SET /A %~2=%RANDOM%*8/32767+1
EXIT /B 0

:DEAD
CALL :CLS
ECHO YOU DIED
PAUSE
EXIT